### ISSUE TITLE
Date fields should be autocomplete and user should be able to type in the date

### ISSUE THREAD

**Issue by ibmuhammadi** [ekhmoi/cargo-company-application#3]
Adding or Editing a Date should not take to calendar. User should be able to type in the date and you should give an auto complete to make it easier to type. This is faster than selecting from calendar. The staff have to create hundreds of AWBs so they need to be quick.

There should be a separate calendar icon next to the date field and if user needs to see the calendar then he will click on that and select from there in that case.

**Comment by ibmuhammadi** [comment]
Ok. Good night to you too. About the date - dont autocomplete - use preformatted "/" and use dd/mm/yyyy so users wont have to type in the dashes - something like this : https://codepen.io/davidelrizzo/pen/emHfG
Also the arrow on the right side to drop down calendar date picker.
Also when user presses up arrow or dn arrow the values change.

**Comment by ekhmoi** [comment]
Please recheck now
