### ISSUE TITLE
Separate Agent collection

### ISSUE THREAD

**Issue by ibmuhammadi** [ekhmoi/cargo-company-application#4]
Agent is still ekhmoi - it should be a separate collection and not user

**Comment by ekhmoi** [comment]
Please give me 1 example of Agent document(what properties agent will have?)
something like

name Jason
lastName Statham
age 77

**Comment by ibmuhammadi** [comment]
Name: RRS Courier, Sialkot

**Comment by ekhmoi** [comment]
Fixed
![screen shot 2017-04-17 at 11 41 03 pm](https://cloud.githubusercontent.com/assets/11752651/25101964/61dd9ec6-23c7-11e7-8c35-1b1a8addb72f.png)
