### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by ibmuhammadi** [ekhmoi/cargo-company-application#5]
3. Validations for email , not null etc mentioned are not in place yet

**Comment by ekhmoi** [comment]
Please describe which fields and how they should be validated ?
min-max symbols allowed characters and etc

**Comment by ibmuhammadi** [comment]
Validations:
Date, time entries should be in proper format. dd/mm/yyyy and 24 hour format for time.
Email validations as usual to check for validity of email
All fields are mandatory - cannot be blank - except for these fields which can be blank:
COD details can be blank
Receiver and sender email can be blank except when the COD details are filled in. When COD details are filled in then the receiver email cannot be blank.

Also as soon as a new AWB is saved (not existing awb edit) then an email should be sent to receiver email (only if COD details are there. Also an sms should be sent to sender. 

Format for sms to sender: Your shipment with tracking number (AWB number here) has been received by our office on (date received) and will be processed for onward delivery. 
You can track your package on our website fte.com.pk
Fast Track Express team

FOrmat of email to receiver in case of COD shipment:
We have received a shipment that is marked as "Cash Payment to be collected from receiver (you)". The shipment was sent by (sender name) to be delivered to you at (name and address of receiver).
Contents of the shipment: (Package contents)
Weight : (Total weight)
Cash on delivery to be paid by you: (COD amount) + (COD description)

We have held the shipment till you confirm via a reply email that this shipment is indeed your order and the above mentioned amount and associated charges will be borne by you.

We will process the shipment only when we receive an email confirmation form you and will hold the shipment at source or return the shipment back to the sender if confirmation is not received in 7 days.
Awaiting your response
Fast track express team
The sms and email formats should be changeable by the users in case they need to customize it

**Comment by ekhmoi** [comment]
@ibmuhammadi please recheck validations.
